server:
  #客户端端口号
  port: 8080
spring:
  application:
    #客户端注册名字 ,在注册中心Application的名字
    name: eureka-client
eureka:
  client:
    #因为是客户端，所以需要自我注册，注册到eureka-server中 默认：true
    register-with-eureka: true
    #从客户端拉取服务，后面你不止用自己一个服务，可能会通过feign接口调用server中别的服务，所以需要拉取服务 默认：true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka #注册中心地址，如果集群，有几个写几个，逗号分隔
  instance:
    # 更倾向使用ip地址，而不是host名
    prefer-ip-address: true
    #注册中心中测项目Status的名字
    instance-id: ${eureka.instance.ip-address}
    # ip地址 这是客户端的注册地址， eureka 会通过这个地址建立管道
    ip-address: 127.0.0.1  #默认0.0.0.0.0.0.1
    # 表示eureka client发送心跳给server端的频率,续约间隔，默认30秒(只要服务端没有接收到，并不会直接剔除，会先把Status变为Down状态)
    lease-renewal-interval-in-seconds: 5
    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 15


